# Generated by Django 5.1.4 on 2025-01-13 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CanteenManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=200)),
                ('perPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('department', models.CharField(choices=[('BEI', 'BEI'), ('BCT', 'BCT'), ('BEL', 'BEL'), ('BME', 'BME'), ('BARCH', 'BARCH'), ('BCE', 'BCE')], default='BEI', max_length=10)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('points', models.IntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='UUIDStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcatedPoints', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('foodOrderes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.canteenmanager')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.studentdata')),
            ],
        ),
        migrations.AddField(
            model_name='studentdata',
            name='uuid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.uuidstudent'),
        ),
    ]
