# Generated by Django 5.1.4 on 2025-01-13 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.uuidstudent'),
        ),
    ]
