# Generated by Django 5.1.4 on 2025-01-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_studentdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uuidOFstudent', to='base.uuidstudent'),
        ),
    ]
